volumes:
  pg_data:
    driver: local
  pdm_docs:
    driver: local
networks:
  pdm_default:
  web:
    external: true
secrets:
  django_secret_key:
    file: /secrets/pdm/secret_key
  document_encryption_key:
    file: /secrets/pdm/document_encryption_key
  mail_password:
    file: /secrets/pdm/mail_password
services:
  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - pdm_default
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn patient_data_management.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    secrets:
      - django_secret_key
      - document_encryption_key
      - mail_password
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - LANGUAGE_CODE=de-de
      - DEBUG=0
      - SECRET_KEY_FILE=/run/secrets/django_secret_key
      - DOCUMENT_ENCRYPTION_KEY_FILE=/run/secrets/document_encryption_key
      - EMAIL_HOST=smtp.strato.de
      - EMAIL_HOST_PASSWORD_FILE=/run/secrets/mail_password
      # - URL_PREFIX=pdm/
    volumes:
      - pdm_docs:/code/documents
    depends_on:
      - db
    networks:
      - pdm_default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pdm.entrypoints=https"
      - "traefik.http.routers.pdm.rule=Host(`pdm.big-sala.me`, `cloud.arne-kapell.de`)"
      - "traefik.http.routers.pdm.tls=true"
      - "traefik.http.routers.pdm.tls.certresolver=http"
      - "traefik.http.services.pdm-svc.loadbalancer.server.port=8000"
      - "traefik.docker.network=web"
  db_backups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    networks:
      - pdm_default
    volumes:
      - ./backup:/backups
    links:
      - db:db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - SCHEDULE=@every 12h00m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      # - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      # - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)

      # Wiederherstellen:
      # docker cp C:\Users\Irina\Documents\GitHub\patient-data-management\backup\daily\postgres-20221204.sql.gz $containerid:/postgres-20221204.sql.gz
      # docker exec --tty --interactive $containerid  /bin/sh -c "zcat postgres-20221204.sql.gz | psql --username=xxxxx --dbname=xxxx -W"
