# Generated by Django 4.1 on 2022-12-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
