# Generated by Django 4.1 on 2022-12-02 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0002_rename_approved_at_accessrequest_approved_or_denied_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("medical_role", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("check_url", models.URLField(null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                ("denied", models.BooleanField(default=False)),
                ("reason", models.TextField(null=True)),
                ("processed_at", models.DateTimeField(null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
