# Generated by Django 4.1 on 2022-12-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Patient"), (2, "Doctor"), (3, "Verificator")], default=1
            ),
        ),
    ]
