# Generated by Django 4.1 on 2022-10-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0002_alter_document_file_alter_document_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="id",
        ),
        migrations.RemoveField(
            model_name="note",
            name="id",
        ),
        migrations.AlterField(
            model_name="document",
            name="uid",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="note",
            name="uid",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
