# Generated by Django 4.1 on 2022-12-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0003_verificationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrequest",
            name="hints",
            field=models.TextField(blank=True),
        ),
    ]
