# Generated by Django 4.1 on 2022-10-07 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0003_remove_document_id_remove_note_id_alter_document_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
