# Generated by Django 4.1 on 2022-12-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0004_verificationrequest_hints"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="birth_date", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="street_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="street_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user", name="last_name", field=models.CharField(max_length=255),
        ),
    ]
