# Generated by Django 4.1 on 2022-10-07 09:40

from django.db import migrations, models
import pdm.models


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0004_alter_document_uid_alter_note_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to=pdm.models.get_upload_path),
        ),
    ]
