# Generated by Django 4.1 on 2022-12-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0005_user_birth_date_user_city_user_country_user_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessrequest", old_name="doctor", new_name="requested_by",
        ),
    ]
