# Generated by Django 4.1 on 2022-12-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0006_rename_doctor_accessrequest_requested_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(auto_created=True),
        ),
    ]
