# Generated by Django 4.1 on 2022-10-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0006_alter_accessrequest_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document", old_name="upload", new_name="uploaded_at",
        ),
    ]
