# Generated by Django 4.1 on 2022-10-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0007_rename_upload_document_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
