# Generated by Django 4.1 on 2022-12-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0007_alter_document_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
