# Generated by Django 4.1 on 2022-12-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdm", "0008_alter_document_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tag_line",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True),
        ),
    ]
