name: Run tests and deploy to VPS
 
on: [push, pull_request, workflow_dispatch]

env:
  HOST: cloud.arne-kapell.de
  USERNAME: ${{ secrets.USERNAME }}
  PORT: ${{ secrets.PORT }}
  KEY: ${{ secrets.SSHKEY }}
  TARGET_PATH: "/repos/pdm/"
  COMPOSE_FILE: "docker-compose.prod.yml"
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test --noinput --debug-mode
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: vps
      url: "https://${{ env.HOST }}/"
    steps:
    - uses: actions/checkout@v1
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ env.HOST }}
        USERNAME: ${{ env.USERNAME }}
        PORT: ${{ env.PORT }}
        KEY: ${{ env.KEY }}
      with:
        source: "./*"
        target: ${{ env.TARGET_PATH }}
        overwrite: true
        rm: true
 
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST }}
        USERNAME: ${{ env.USERNAME }}
        PORT: ${{ env.PORT }}
        KEY: ${{ env.SSHKEY }}
        script: |
          cd ${{ env.TARGET_PATH }}
          docker compose -f ${{ env.COMPOSE_FILE }} up -d --build --force-recreate --remove-orphans > ACTION_DEPLOY.log