name: Deploy to VPS
 
on: [push, pull_request, workflow_dispatch]

env:
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  PORT: ${{ secrets.PORT }}
  KEY: ${{ secrets.SSHKEY }}
  TARGET_PATH: "/repos/pdm"
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ env.HOST }}
        USERNAME: ${{ env.USERNAME }}
        PORT: ${{ env.PORT }}
        KEY: ${{ env.SSHKEY }}
      with:
        source: "."
        target: ${{ env.TARGET_PATH }}
 
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST }}
        USERNAME: ${{ env.USERNAME }}
        PORT: ${{ env.PORT }}
        KEY: ${{ env.SSHKEY }}
        script: |
          cd ${{ env.TARGET_PATH }}
          docker-compose down
          docker-compose -f docker-compose.prod.yml up -d --build
