name: Deploy to VPS
 
on: [push, pull_request, workflow_dispatch]

env:
  HOST: cloud.arne-kapell.de
  USERNAME: ${{ secrets.USERNAME }}
  PORT: ${{ secrets.PORT }}
  KEY: ${{ secrets.SSHKEY }}
  TARGET_PATH: "/repos/pdm/"
  COMPOSE_FILE: "docker-compose.prod.yml"
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: vps
      url: "https://${{ env.HOST }}/pdm/"
    steps:
    - name: start deployment
      uses: bobheadxi/deployments@v1
      id: deployment
      with:
        step: start
        token: ${{ secrets.GH_TOKEN }}
        env: vps
    - uses: actions/checkout@v1
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ env.HOST }}
        USERNAME: ${{ env.USERNAME }}
        PORT: ${{ env.PORT }}
        KEY: ${{ env.KEY }}
      with:
        source: "./*"
        target: ${{ env.TARGET_PATH }}
 
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST }}
        USERNAME: ${{ env.USERNAME }}
        PORT: ${{ env.PORT }}
        KEY: ${{ env.SSHKEY }}
        script: |
          cd ${{ env.TARGET_PATH }}
          docker compose -f ${{ env.COMPOSE_FILE }} up -d --build --force-recreate --remove-orphans > ACTION_DEPLOY.log
    - name: update deployment status
      uses: bobheadxi/deployments@v1
      if: always()
      with:
        step: finish
        token: ${{ secrets.GH_TOKEN }}
        status: ${{ job.status }}
        env: vps
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
